const fishData=[
 {r:'쓰레기',p:0,c:30,cls:'trash',items:[['🥫','찌그러진 깡통'],['🥾','해적의 장화'],['🛞','낡은 타이어'],['🪥','바다 칫솔']]},
 {r:'흔한 물고기',p:10,c:40,cls:'common',items:[['🐟','은빛 멸치'],['🦑','통통한 오징어'],['🐡','복어'],['🐠','산호돔']]},
 {r:'희귀 물고기',p:50,c:20,cls:'rare',items:[['🐙','별빛 문어'],['🦞','푸른 가재'],['🐟','무지개 고등어'],['🐡','달빛 복어']]},
 {r:'전설의 물고기',p:100,c:10,cls:'legendary',items:[['🦈','심해 상어'],['🐳','고래의 노래'],['🐉','바다의 용'],['🦄','유니콘 피쉬']]}
];
const $=id=>document.getElementById(id);
const el={score:$('score'),coins:$('coins'),level:$('level'),xp:$('xpBar'),xpText:$('xpText'),button:$('fishButton'),status:$('statusLabel'),message:$('catchMessage'),line:$('line'),bobber:$('bobber'),timing:$('timingArea'),needle:$('meterNeedle'),logs:$('logList'),grid:$('collectionGrid'),combo:$('combo'),badge:$('comboBadge'),toast:$('toast')};
let game=JSON.parse(localStorage.getItem('oceanCatchSave'))||{score:0,coins:0,combo:0,found:[],logs:[]},state='idle',needleTimer,biteTimer,soundOn=true;
function save(){localStorage.setItem('oceanCatchSave',JSON.stringify(game))}function level(){return Math.floor(game.score/100)+1}function toast(t){el.toast.textContent=t;el.toast.classList.add('show');setTimeout(()=>el.toast.classList.remove('show'),2200)}
function render(){el.score.textContent=game.score.toLocaleString();el.coins.textContent=game.coins.toLocaleString();el.level.textContent=level();let xp=game.score%100;el.xp.style.width=xp+'%';el.xpText.textContent=`다음 레벨까지 ${100-xp} XP`;el.combo.textContent=game.combo;el.badge.hidden=game.combo<2;el.grid.innerHTML='';fishData.flatMap(x=>x.items).forEach(([emoji,name])=>{let s=document.createElement('span');s.textContent=emoji;s.title=name;if(game.found.includes(name))s.className='found';el.grid.append(s)});el.logs.innerHTML=game.logs.length?'': '<li class="empty-log">첫 번째 낚시를 기다리고 있어요…</li>';game.logs.forEach(x=>{let li=document.createElement('li');li.innerHTML=`<span>${x.emoji} ${x.name}</span><b class="rarity ${x.cls}">${x.r} · +${x.points}</b>`;el.logs.append(li)})}
function pick(){let n=Math.random()*100,total=0;for(const group of fishData){total+=group.c;if(n<total)return group}}
function sound(freq=440,d=.07){if(!soundOn||!window.AudioContext)return;let a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.04,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+d);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+d)}
function cast(){if(state==='idle'){state='waiting';el.button.disabled=true;el.button.innerHTML='🌊 기다리는 중…';el.status.textContent='미끼가 물속으로 가라앉고 있습니다…';document.querySelector('.ocean-card').classList.add('casting');sound(310);biteTimer=setTimeout(bite,900+Math.random()*1700)}else if(state==='bite'){resolve(Number(el.needle.dataset.pos))}}
function bite(){state='bite';document.querySelector('.ocean-card').classList.add('biting');el.timing.hidden=false;el.button.disabled=false;el.button.innerHTML='⚡ 지금 당기기!';el.status.textContent='입질이다! 황금 구간을 노려보세요!';let start=performance.now();function move(now){if(state!=='bite')return;let p=((now-start)%1250)/1250*100;el.needle.style.left=p+'%';el.needle.dataset.pos=p;needleTimer=requestAnimationFrame(move)}needleTimer=requestAnimationFrame(move);setTimeout(()=>{if(state==='bite')miss()},3000);sound(720,.12)}
function miss(){state='idle';cancelAnimationFrame(needleTimer);game.combo=0;resetSea();el.status.textContent='앗, 물고기가 도망갔어요!';el.message.textContent='다음엔 더 정확하게 낚아 보세요.';el.button.disabled=false;el.button.innerHTML='🎣 다시 던지기';render();save();sound(180,.15)}
function resolve(p){cancelAnimationFrame(needleTimer);let perfect=p>=43&&p<=61;let good=p>=35&&p<=69;if(!good){miss();return}let caught=pick(),item=caught.items[Math.floor(Math.random()*caught.items.length)],bonus=perfect?Math.min(game.combo*2,30):0,earned=caught.p+bonus;game.score+=earned;game.coins+=Math.max(1,Math.floor(earned/2));game.combo++;if(!game.found.includes(item[1])){game.found.push(item[1]);toast(`✨ 새 도감 발견: ${item[1]}!`)}game.logs.unshift({emoji:item[0],name:item[1],r:caught.r,cls:caught.cls,points:earned});game.logs=game.logs.slice(0,12);state='idle';resetSea();el.status.textContent=perfect?'PERFECT CAST! 보너스가 적용됐어요.':'좋은 타이밍이에요!';el.message.textContent=`${item[0]} ${item[1]}을(를) 낚았습니다! +${earned}점`;el.button.disabled=false;el.button.innerHTML='🎣 한 번 더 낚시하기';render();save();sound(perfect?900:580,.16)}
function resetSea(){clearTimeout(biteTimer);document.querySelector('.ocean-card').classList.remove('casting','biting');el.timing.hidden=true}
el.button.addEventListener('click',cast);$('resetButton').addEventListener('click',()=>{if(confirm('점수와 도감까지 모두 초기화할까요?')){game={score:0,coins:0,combo:0,found:[],logs:[]};save();render();toast('새로운 항해를 시작합니다!')}});$('soundButton').addEventListener('click',e=>{soundOn=!soundOn;e.currentTarget.textContent=soundOn?'🔊':'🔇'});render();
